name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

permissions:
  contents: read

jobs:
  Linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install requests
          pip3 install tencentcloud-sdk-python
          pip3 install pillow
      - name: Build
        run: |
          python3 -m PyInstaller main.py -F -i icon.ico
          mv dist/main dist/qcip
          mv config.json dist/config.json
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-linux-x64
          path: dist/*
  Windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install requests
          pip3 install tencentcloud-sdk-python
          pip3 install pillow
      - name: Build
        run: |
          python3 -m PyInstaller main.py -F -i icon.ico --upx-dir upx
          mv dist/main.exe dist/qcip.exe
          mv config.json dist/config.json
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-windows-x64
          path: dist/*
  MacOS:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install requests
          pip3 install tencentcloud-sdk-python
          pip3 install pillow
      - name: Build
        run: |
          python3 -m PyInstaller main.py -F -i icon.ico
          mv dist/main dist/qcip
          mv config.json dist/config.json
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-macos-x64
          path: dist/*
