name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install requests
          pip3 install tencentcloud-sdk-python
      - name: Build
        run: |
          python3 -m PyInstaller main.py -F -i icon.ico
          mv dist/main dist/qcip
          mv config.json dist/config.json
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-linux-x86_64
          path: dist/*
  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install requests
          pip3 install tencentcloud-sdk-python
          pip3 install pillow
      - name: Build
        run: |
          python3 -m PyInstaller main.py -F -i icon.ico
          mv dist/main.exe dist/qcip.exe
          mv config.json dist/config.json
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-windows-x86_64
          path: dist/*
  build_on_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install requests
          pip3 install tencentcloud-sdk-python
      - name: Build
        run: |
          python3 -m PyInstaller main.py -F -i icon.ico
          mv dist/main dist/qcip
          mv config.json dist/config.json
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-macos-x86_64
          path: dist/*
