name: Build

on:
    workflow_dispatch:
      inputs:
        version:
          description: "Version"
          required: true
          type: string
        create_release:
          description: 'Create Release'  
          required: false
          default: false
          type: boolean

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20'
      - name: Build
        run: |
            chmod 755 build.sh
            ./build.sh ${{ github.event.inputs.version }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: dist/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.create_release == 'true' }}
        with:
          files: dist/*
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          body: |
            #### What's changed
            - 
          token: ${{ secrets.GHTOKEN }}