name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

permissions:
  contents: read

jobs:
  Linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"  
      - name: Install dependencies
        run: |
          sudo python3 -m pip install --upgrade pip
          pip3 install --user nuitka
          sudo pip3 install tencentcloud-sdk-python
          sudo pip3 install requests
          sudo pip3 install termcolor
          sudo apt-get install -y gcc
          sudo apt-get install -y python3-dev
      - name: Build
        run: |
          sed -i "11i\version = colored('Linux version ', 'light_yellow') + colored('${{ github.event.inputs.version }}', 'green')" main.py
          " main.py
          python3 -m nuitka --standalone --onefile --follow-imports -o qcip main.py
          mkdir artifact
          cp config.json artifact/config.json
          cp qcip artifact/qcip
          zip -r qcip-${{ github.event.inputs.version }}-linux-amd64.zip artifact/*
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: qcip-${{ github.event.inputs.version }}-linux-amd64.zip

  Windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"  
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install tencentcloud-sdk-python
          pip3 install nuitka
          pip3 install requests
          pip3 install termcolor
          choco install visualstudio2019buildtools -y
          choco install sed
      - name: Build
        run: |
          sed -i "11i\version = colored('Windows version ', 'light_yellow') + colored('${{ github.event.inputs.version }}', 'green')" main.py
          python3 -m nuitka --standalone --onefile --experimental=use-pefile --follow-imports -o qcip.exe --assume-yes-for-downloads main.py 
          mkdir artifact
          cp config.json artifact/config.json
          cp qcip.exe artifact/qcip.exe
          powershell Compress-Archive -Path artifact\* -DestinationPath qcip-${{ github.event.inputs.version }}-windows-amd64.zip
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: qcip-${{ github.event.inputs.version }}-windows-amd64.zip
          
  MacOS:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3       
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install dependencies 
        run: |
          brew install python@3.10
          sudo python3 -m pip install --upgrade pip
          sudo pip3 install tencentcloud-sdk-python
          sudo pip3 install requests
          sudo pip3 install termcolor
          sudo pip3 install nuitka
      - name: Build
        run: |
          sed -i '' '11i\
          version = colored('"'"'MacOS version '"'"', '"'"'light_yellow'"'"') + colored('\''${{ github.event.inputs.version }}'\'', '"'"'green'"'"')' main.py
          python3 -m nuitka --standalone --onefile --follow-imports -o qcip main.py
          mkdir artifact
          cp config.json artifact/config.json
          cp qcip artifact/qcip
          zip -r qcip-${{ github.event.inputs.version }}-macos-amd64.zip artifact/*
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: qcip-${{ github.event.inputs.version }}-macos-amd64.zip
          
  Source:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Wrapping
        run: |
          sed -i "11i\version = colored('Python version ', 'light_yellow') + colored('${{ github.event.inputs.version }}', 'green')" main.py
          mkdir artifact
          cp main.py artifact/main.py
          cp config.json artifact/config.json
          zip -r qcip-${{ github.event.inputs.version }}-source.zip artifact/*
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: qcip-${{ github.event.inputs.version }}-source.zip
  MD5:
    runs-on: ubuntu-22.04
    needs: [Linux, Windows, MacOS, Source]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: artifact
      - name: Generate MD5
        run: |
          cd artifact
          md5sum * > md5.txt
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: artifact/md5.txt