name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

permissions:
  contents: read

jobs:
  Linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"  
      - name: Install dependencies
        run: |
          sudo python3 -m pip install --upgrade pip
          pip3 install --user nuitka
          sudo pip3 install requests
          sudo apt-get install -y gcc
          sudo apt-get install -y python3-dev
      - name: Build
        run: |
          python3 -m nuitka --standalone --onefile --follow-imports -o qcip main.py
          mkdir artifact
          cp config.json artifact/config.json
          cp qcip artifact/qcip
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-linux-amd64
          path: artifact/*
          
  Windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"  
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install nuitka
          pip3 install requests
          choco install visualstudio2019buildtools -y
      - name: Build
        run: |
          python3 -m nuitka --standalone --onefile --experimental=use-pefile --follow-imports -o qcip.exe --assume-yes-for-downloads main.py 
          mkdir artifact
          cp config.json artifact/config.json
          cp qcip.exe artifact/qcip.exe
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-windows-amd64
          path: artifact/*
          
  MacOS:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3       
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          brew install python@3.10
          sudo python3 -m pip install --upgrade pip
          sudo pip3 install requests
          sudo pip3 install nuitka
      - name: Build
        run: |
          python3 -m nuitka --standalone --onefile --follow-imports -o qcip main.py
          mkdir artifact
          cp config.json artifact/config.json
          cp qcip artifact/qcip
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-macos-amd64
          path: artifact/*
  Source:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Wrapping
        run: |
          mkdir artifact
          cp main.py artifact/main.py
          cp config.json artifact/config.json
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: qcip-${{ github.event.inputs.version }}-source
          path: artifact/*

